# Generated by Django 4.2.7 on 2024-07-30 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directorio', '0004_rename_condicion_alumno_condicion_alumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condicion_Alumnos',
            new_name='Condicion_Alumno',
        ),
    ]
